# --------------
# -- Settings --
# --------------

url: "https://danielnjoo.github.io/hackamherst"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-111222072-1"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "Hack Amherst | 3-4 March 2018"
  description: "This is the website for Amherst College's hackathon: Hack Amherst."
  image:       "/images/favicon.png"

# Event information.
event:
  name:        "HackAmherst"
  video:       "videos/01.mp4"
  date:        "3-4 March 2018"
  location:    "Amherst, MA, United States"
  hero:
    links:
      - text: "Follow Us"
        href: "https://www.facebook.com/HackAmherst/"
      # - text: "Mailing List"
      #   href: ""

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
