# --------------
# -- Settings --
# --------------

url: "https://danielnjoo.github.io/hackamherst"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-111222072-1"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "Hack Amherst | 3-4 March 2018"
  description: "This is the website for Amherst College's hackathon: Hack Amherst."
  image:       "/images/favicon.png"

# Event information.
event:
  name:        "HackAmherst"
  video:       "videos/01.mp4"
  date:        "3-4 March 2018"
  location:    "Amherst, MA, United States"
  hero:
    links:
      - text: "Register"
        href: "https://docs.google.com/forms/d/e/1FAIpQLSdPJFotXuZ9YrvKFHpEP_4cbCGANggMKp6h74H5ciNaoLPVKw/viewform?usp=sf_link"
      - text: "Sponsor"
        href: "https://drive.google.com/file/d/1HovcWP55Bhi5GKGq7fvH3pVDWAWFL0tW/view?usp=sharing"

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
