# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "https://danielnjoo.github.io/mlh-hackathon-boilerplate"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
# social:
#   twitter_handle: "MLHacks"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "Hack Amherst | 3-4 March 2018"
  description: "This is the website for Hack Amherst."
  image:       "https://prime.mlh.io/img/logos/mlh-prime-color.svg"

# Event information.
event:
  name:        "Hack Amherst"
  video:       "videos/01.mp4"
  date:        "3-4 March 2018"
  location:    "Amherst, MA, United States"
  hero:
    links:
      - text: "Register"
        href: "https://docs.google.com/forms/d/e/1FAIpQLSe4Jukf1TwC144flKzcHoE1VCWsZS6IEYifX4LKpbRj0ASSAQ/viewform?usp=sf_link"
      - text: "Sponsor"
        href: "mailto:dnjoo20@amherst.edu"

  about:
    description: >
      Hack Amherst is a hackathon hosted at Amherst College...

  # Info Sections
  info:
    sections:
      - image: "images/image1.png"
        title: "LEARN."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.
      - image: "images/image2.png"
        title: "BUILD."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.
      - image: "images/image3.png"
        title: "SHARE."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
